// AUTOGENERATED from ../youtube-ai-system/core/brand_config.py
// DO NOT EDIT BY HAND. Run: npm run gen-brands
// CI drift check: package.json prebuild fails if this file is stale.

export type BrandId = 'nuvox_ai' | 'nuvox_space' | 'nuvox_world';
export type BrandSlug = 'nuvoxai' | 'nuvoxspace' | 'nuvoxworld';

export interface BrandPalette {
  readonly primary: string;
  readonly cyan: string;
  readonly purple: string;
  readonly gold: string;
  readonly dark: string;
  readonly card: string;
  readonly overlay: string;
}

export interface Brand {
  readonly id: BrandId;
  readonly slug: BrandSlug;
  readonly path: string;
  readonly name: string;
  readonly handle: string;
  readonly niche: string;
  readonly palette: BrandPalette;
}

export const BRANDS: ReadonlyArray<Brand> = [
  {
    "id": "nuvox_ai",
    "slug": "nuvoxai",
    "path": "/nuvoxai/",
    "name": "Nuvox AI",
    "handle": "@nuvoxai",
    "niche": "ai_tech",
    "palette": {
      "primary": "#00B4FF",
      "cyan": "#00E5FF",
      "purple": "#7B2FFF",
      "gold": "#FFD700",
      "dark": "#0A0A0A",
      "card": "#121218",
      "overlay": "#1A1A2E"
    }
  },
  {
    "id": "nuvox_space",
    "slug": "nuvoxspace",
    "path": "/nuvoxspace/",
    "name": "Nuvox Space",
    "handle": "@nuvoxspace",
    "niche": "space_astronomy",
    "palette": {
      "primary": "#1E90FF",
      "cyan": "#00CED1",
      "purple": "#4B0082",
      "gold": "#FFD700",
      "dark": "#0B0B1A",
      "card": "#0F0F24",
      "overlay": "#141432"
    }
  },
  {
    "id": "nuvox_world",
    "slug": "nuvoxworld",
    "path": "/nuvoxworld/",
    "name": "Nuvox World",
    "handle": "@nuvoxworld",
    "niche": "world_facts",
    "palette": {
      "primary": "#DC143C",
      "cyan": "#00B4D8",
      "purple": "#5B2C6F",
      "gold": "#FFD700",
      "dark": "#0A0A0A",
      "card": "#121218",
      "overlay": "#1A1A2E"
    }
  }
] as const;

export const BRAND_BY_ID: Readonly<Record<BrandId, Brand>> = Object.fromEntries(
  BRANDS.map((b) => [b.id, b]),
) as Record<BrandId, Brand>;

export const BRAND_BY_SLUG: Readonly<Record<BrandSlug, Brand>> = Object.fromEntries(
  BRANDS.map((b) => [b.slug, b]),
) as Record<BrandSlug, Brand>;
