/**
 * Codegen: ../youtube-ai-system/core/brand_config.py
 *  → lib/brands.ts                       (typed brand registry)
 *  → app/_brand-vars.generated.css       (per-brand CSS vars, single source of truth)
 *  → tokens/raw/brands.json              (JSON dump for downstream tools — Penpot sync etc.)
 *
 * Run:  npm run gen-brands
 * CI:   prebuild script fails if any output is stale
 *
 * Web allowlist is read from web-brands.config.json (was hardcoded — Phase 11
 * Engineer review #3). Letting a brand ship to YouTube before it ships to
 * web no longer requires editing this file.
 *
 * Phase 11 review #5: style-dictionary was installed but unused. The CSS
 * generation in this script makes it redundant — dep is removed. The
 * tokens/raw/brands.json output is kept as a generic JSON view for any
 * future external tool that wants brand data (Penpot, design system, etc.).
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import path from 'node:path';

const SRC = path.resolve('../youtube-ai-system/core/brand_config.py');
const DST_TS = path.resolve('lib/brands.ts');
const DST_CSS = path.resolve('app/_brand-vars.generated.css');
const DST_TOKENS = path.resolve('tokens/raw/brands.json');
const ALLOWLIST_PATH = path.resolve('web-brands.config.json');

// ─────────────────────────────────────────────────────────────────────────
// Allowlist — externalised. web-brands.config.json controls which brands
// ship to the website. Python BRAND_REGISTRY may grow ahead of web.
// ─────────────────────────────────────────────────────────────────────────
interface AllowlistConfig {
  brands: string[];
  /** Public URL segment per brand on the website (e.g. nuvox_space -> "space"). */
  webSlugs?: Record<string, string>;
}

function readConfig(): AllowlistConfig {
  if (!existsSync(ALLOWLIST_PATH)) {
    throw new Error(
      `${ALLOWLIST_PATH} missing. Create it with {"brands":["nuvox_ai","nuvox_space","nuvox_world"]}`,
    );
  }
  const cfg = JSON.parse(readFileSync(ALLOWLIST_PATH, 'utf8')) as AllowlistConfig;
  if (!Array.isArray(cfg.brands) || cfg.brands.length === 0) {
    throw new Error(`${ALLOWLIST_PATH}: "brands" must be a non-empty array`);
  }
  for (const b of cfg.brands) {
    if (!/^nuvox_[a-z0-9_]+$/.test(b)) {
      throw new Error(`${ALLOWLIST_PATH}: invalid brand id "${b}"`);
    }
  }
  for (const [id, slug] of Object.entries(cfg.webSlugs ?? {})) {
    if (!/^[a-z0-9-]{1,40}$/.test(slug)) throw new Error(`${ALLOWLIST_PATH}: invalid web slug "${slug}" for ${id}`);
  }
  return cfg;
}

// CI/Vercel only have THIS repo checked out — the sibling
// youtube-ai-system path doesn't exist on those builders. The committed
// outputs (lib/brands.ts etc.) are the source of truth in CI; gen-brands
// is a developer-side regeneration tool gated by the prebuild drift check.
// When source is absent, exit 0 with a note — the drift check that follows
// in `npm run prebuild` will pass because nothing was modified.
if (!existsSync(SRC)) {
  console.log(`[gen-brands] skip: source not present at ${SRC} (CI build — using committed outputs).`);
  process.exit(0);
}

const CONFIG = readConfig();
const ALLOWED = CONFIG.brands;
const py = readFileSync(SRC, 'utf8');

function extractBrandBlock(brandId: string): string {
  // Brands are declared as module-level constants: _NUVOX_AI = BrandConfig(...)
  const constName = `_${brandId.toUpperCase()}`;
  const re = new RegExp(`${constName}\\s*=\\s*BrandConfig\\(([\\s\\S]*?)\\n\\)`, 'g');
  const m = re.exec(py);
  if (!m) throw new Error(`brand block not found: ${brandId} (looked for ${constName})`);
  return m[1];
}

function strField(block: string, name: string): string {
  const re = new RegExp(`${name}=["']([^"']+)["']`);
  const m = block.match(re);
  if (!m) throw new Error(`field ${name} not found`);
  return m[1];
}

function paletteFrom(block: string): Record<string, string> {
  const m = block.match(/brand_colors=\{([\s\S]*?)\}/);
  if (!m) throw new Error('brand_colors block not found');
  const out: Record<string, string> = {};
  const re = /["'](\w+)["']\s*:\s*["'](#[0-9A-Fa-f]{3,8})["']/g;
  let mm;
  while ((mm = re.exec(m[1]))) out[mm[1]] = mm[2];
  return out;
}

const BRANDS = ALLOWED.map((id) => {
  const block = extractBrandBlock(id);
  const slug = CONFIG.webSlugs?.[id] ?? strField(block, 'blog_tag');
  return {
    id,
    slug,
    path: `/${slug}/`,
    name: strField(block, 'channel_name'),
    handle: strField(block, 'channel_handle'),
    niche: strField(block, 'niche'),
    palette: paletteFrom(block),
  };
});

// ─────────────────────────────────────────────────────────────────────────
// Output 1: lib/brands.ts (typed registry)
// ─────────────────────────────────────────────────────────────────────────
const ts = `// AUTOGENERATED from ../youtube-ai-system/core/brand_config.py
// DO NOT EDIT BY HAND. Run: npm run gen-brands
// CI drift check: package.json prebuild fails if this file is stale.

export type BrandId = ${ALLOWED.map((b) => `'${b}'`).join(' | ')};
export type BrandSlug = ${BRANDS.map((b) => `'${b.slug}'`).join(' | ')};

export interface BrandPalette {
  readonly primary: string;
  readonly cyan: string;
  readonly purple: string;
  readonly gold: string;
  readonly dark: string;
  readonly card: string;
  readonly overlay: string;
}

export interface Brand {
  readonly id: BrandId;
  readonly slug: BrandSlug;
  readonly path: string;
  readonly name: string;
  readonly handle: string;
  readonly niche: string;
  readonly palette: BrandPalette;
}

export const BRANDS: ReadonlyArray<Brand> = ${JSON.stringify(BRANDS, null, 2)} as const;

export const BRAND_BY_ID: Readonly<Record<BrandId, Brand>> = Object.fromEntries(
  BRANDS.map((b) => [b.id, b]),
) as Record<BrandId, Brand>;

export const BRAND_BY_SLUG: Readonly<Record<BrandSlug, Brand>> = Object.fromEntries(
  BRANDS.map((b) => [b.slug, b]),
) as Record<BrandSlug, Brand>;
`;
writeFileSync(DST_TS, ts);

// ─────────────────────────────────────────────────────────────────────────
// Output 2: app/_brand-vars.generated.css (per-brand CSS vars)
// ─────────────────────────────────────────────────────────────────────────
function escapeCssIdent(s: string): string {
  // brand ids match /^nuvox_[a-z0-9_]+$/ — already CSS-attr-safe but be paranoid
  return s.replace(/[^a-z0-9_]/g, '');
}

const cssBlocks = BRANDS.map((b) => {
  const id = escapeCssIdent(b.id);
  const p = b.palette;
  return `[data-brand="${id}"] {
  --brand: ${p.primary};
  --brand-cyan: ${p.cyan};
  --brand-purple: ${p.purple};
  --brand-gold: ${p.gold};
  --brand-dark: ${p.dark};
  --brand-card: ${p.card};
  --brand-overlay: ${p.overlay};
}`;
}).join('\n\n');

const css = `/* AUTOGENERATED from ../youtube-ai-system/core/brand_config.py
 * DO NOT EDIT BY HAND. Run: npm run gen-brands
 * Imported by app/globals.css. Phase 11 review item #1. */

${cssBlocks}
`;
writeFileSync(DST_CSS, css);

// ─────────────────────────────────────────────────────────────────────────
// Output 3: tokens/raw/brands.json (Style Dictionary input — Phase 11 #5)
// Wires the previously-empty tokens/ pipeline so style-dictionary has data.
// ─────────────────────────────────────────────────────────────────────────
const tokensDir = path.dirname(DST_TOKENS);
if (!existsSync(tokensDir)) mkdirSync(tokensDir, { recursive: true });

const tokensInput: Record<string, unknown> = { color: { brand: {} as Record<string, unknown> } };
for (const b of BRANDS) {
  (tokensInput.color as { brand: Record<string, unknown> }).brand[b.id] = Object.fromEntries(
    Object.entries(b.palette).map(([k, v]) => [k, { value: v, type: 'color' }]),
  );
}
writeFileSync(DST_TOKENS, JSON.stringify(tokensInput, null, 2));

console.log(`✓ Wrote ${DST_TS}`);
console.log(`✓ Wrote ${DST_CSS}`);
console.log(`✓ Wrote ${DST_TOKENS}`);
console.log(`  ${BRANDS.length} brands: ${BRANDS.map((b) => b.id).join(', ')}`);
