/**
 * Codegen: ../youtube-ai-system/core/brand_config.py → lib/brands.ts
 *
 * Run: npm run gen-brands
 * CI drift check: package.json prebuild script fails if lib/brands.ts is stale
 *
 * Drops nuvox_sports — only nuvox_ai, nuvox_space, nuvox_world ship.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const SRC = path.resolve('../youtube-ai-system/core/brand_config.py');
const DST = path.resolve('lib/brands.ts');

const ALLOWED = ['nuvox_ai', 'nuvox_space', 'nuvox_world'] as const;
type AllowedId = (typeof ALLOWED)[number];

const py = readFileSync(SRC, 'utf8');

function extractBrandBlock(brandId: AllowedId): string {
  // Brands are declared as module-level constants: _NUVOX_AI = BrandConfig(...)
  // Closing paren is at column 0.
  const constName = `_${brandId.toUpperCase()}`;
  const re = new RegExp(
    `${constName}\\s*=\\s*BrandConfig\\(([\\s\\S]*?)\\n\\)`,
    'g',
  );
  const m = re.exec(py);
  if (!m) throw new Error(`brand block not found: ${brandId} (looked for ${constName})`);
  return m[1];
}

function strField(block: string, name: string): string {
  const re = new RegExp(`${name}=["']([^"']+)["']`);
  const m = block.match(re);
  if (!m) throw new Error(`field ${name} not found`);
  return m[1];
}

function paletteFrom(block: string): Record<string, string> {
  const m = block.match(/brand_colors=\{([\s\S]*?)\}/);
  if (!m) throw new Error('brand_colors block not found');
  const out: Record<string, string> = {};
  const re = /["'](\w+)["']\s*:\s*["'](#[0-9A-Fa-f]{3,8})["']/g;
  let mm;
  while ((mm = re.exec(m[1]))) out[mm[1]] = mm[2];
  return out;
}

const BRANDS = ALLOWED.map((id) => {
  const block = extractBrandBlock(id);
  return {
    id,
    slug: strField(block, 'blog_tag'),
    path: strField(block, 'blog_path'),
    name: strField(block, 'channel_name'),
    handle: strField(block, 'channel_handle'),
    niche: strField(block, 'niche'),
    palette: paletteFrom(block),
  };
});

const ts = `// AUTOGENERATED from ../youtube-ai-system/core/brand_config.py
// DO NOT EDIT BY HAND. Run: npm run gen-brands
// CI drift check: package.json prebuild fails if this file is stale.

export type BrandId = ${ALLOWED.map((b) => `'${b}'`).join(' | ')};
export type BrandSlug = ${BRANDS.map((b) => `'${b.slug}'`).join(' | ')};

export interface BrandPalette {
  readonly primary: string;
  readonly cyan: string;
  readonly purple: string;
  readonly gold: string;
  readonly dark: string;
  readonly card: string;
  readonly overlay: string;
}

export interface Brand {
  readonly id: BrandId;
  readonly slug: BrandSlug;
  readonly path: string;
  readonly name: string;
  readonly handle: string;
  readonly niche: string;
  readonly palette: BrandPalette;
}

export const BRANDS: ReadonlyArray<Brand> = ${JSON.stringify(BRANDS, null, 2)} as const;

export const BRAND_BY_ID: Readonly<Record<BrandId, Brand>> = Object.fromEntries(
  BRANDS.map((b) => [b.id, b]),
) as Record<BrandId, Brand>;

export const BRAND_BY_SLUG: Readonly<Record<BrandSlug, Brand>> = Object.fromEntries(
  BRANDS.map((b) => [b.slug, b]),
) as Record<BrandSlug, Brand>;
`;

writeFileSync(DST, ts);
console.log(`✓ Wrote ${DST}`);
console.log(`  ${BRANDS.length} brands: ${BRANDS.map((b) => b.id).join(', ')}`);
